image: registry.labs.nic.cz/turris/turris-build

stages:
  - build
  - verify

Applying patches for Omnia:
  stage: build
  script:
    - './compile_pkgs prepare -t omnia'

Generate pkglists:
  stage: build
  script:
    - './generate_lists --debug'
  artifacts:
      name: "Generated package lists"
      paths:
          - generated_lists/*

Check for generated pkglists:
  stage: verify
  needs: ["Generate pkglists"]
  script:
    - find generated_lists -type f -name '*.lua' -printf '-- %P --\n' -exec luac5.1 -p '{}' \;
