image: registry.labs.nic.cz/turris/os/build

stages:
  - build
  - verify

## Package build prepare #########################################################
.prepare:
  stage: build
  script:
    - './compile_pkgs -t "$BOARD" prepare'


prepare_mox:
  extends: .prepare
  variables:
    BOARD: mox

prepare_omnia:
  extends: .prepare
  variables:
    BOARD: omnia

prepare_turris1x:
  extends: .prepare
  variables:
    BOARD: turris1x

## Medkit ########################################################################
.medkit:
  stage: build
  script:
    - './generate_medkits -t "$BOARD" $(. defaults.sh && [ "$PUBLISH_BRANCH" = "hbs" ] && echo -b hbk)'
    - '[ -f "generated_medkits/$BOARD-medkit-latest.tar.gz" ]'
    - '[ -f "generated_medkits/$BOARD-medkit-min-latest.tar.gz" ]'


medkit_mox:
  extends: .medkit
  variables:
    BOARD: mox

medkit_omnia:
  extends: .medkit
  variables:
    BOARD: omnia

medkit_turris1x:
  extends: .medkit
  variables:
    BOARD: turris1x

## Updater lists #################################################################
lists_generate:
  stage: build
  script:
    - './generate_lists --debug'
  artifacts:
      name: "Generated package lists"
      paths:
          - generated_lists/*
