default:
  image: ubuntu:latest

stages:
  - build

Try to apply patches - Omnia:
  stage: build
  before_script:
    - apt-get update; apt-get -y install  build-essential git ncurses-dev gawk unzip python file wget rsync
    - useradd test
  script:
    - su test -c './compile_pkgs prepare -t omnia'
