image: $CI_REGISTRY_IMAGE

stages:
  - docker
  - build
  - verify

## Docker stage ##################################################################
docker:
  stage: docker
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker
  services:
    - $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:dind
  tags:
    - dind
    - privileged
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE || true
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE --file .gitlab-ci/Dockerfile .gitlab-ci
    - docker push $CI_REGISTRY_IMAGE


## Package build prepare #########################################################
.prepare:
  stage: build
  script:
    - './compile_pkgs -t "$BOARD" prepare'


prepare_mox:
  extends: .prepare
  variables:
    BOARD: mox

prepare_omnia:
  extends: .prepare
  variables:
    BOARD: omnia

prepare_turris1x:
  extends: .prepare
  variables:
    BOARD: turris1x

## Medkit ########################################################################
.medkit:
  stage: build
  script:
    - './generate_medkits -t "$BOARD" $(. defaults.sh && [ "$PUBLISH_BRANCH" = "hbs" ] && echo -b hbk)'
    - '[ -f "generated_medkits/$BOARD-medkit-latest.tar.gz" ]'
    - '[ -f "generated_medkits/$BOARD-medkit-min-latest.tar.gz" ]'


medkit_mox:
  extends: .medkit
  variables:
    BOARD: mox

medkit_omnia:
  extends: .medkit
  variables:
    BOARD: omnia

medkit_turris1x:
  extends: .medkit
  variables:
    BOARD: turris1x

## Updater lists #################################################################
lists_generate:
  stage: build
  script:
    - './generate_lists --debug'
  artifacts:
      name: "Generated package lists"
      paths:
          - generated_lists/*
