default:
  image: registry.labs.nic.cz/turris/turris-build

stages:
  - build

Applying patches for Omnia:
  stage: build
  script:
    - './compile_pkgs prepare -t omnia'

Generate pkglists:
  stage: build
  script:
    - './generate_lists --debug'

Check generated pkglists:
  stage: build
  script:
    - './generate_lists'
    - find generated_lists -type f -name '*.lua' -printf '-- %P --\n' -exec luac5.1 -p '{}' \;
